apiVersion: batch/v1
kind: Job
metadata:
  name: users-migration
  namespace: portfolio
  labels:
    app.kubernetes.io/name: users-migration
    app.kubernetes.io/part-of: portfolio
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: users-migration
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: ghcr.io/szymonborowski/microservices-users:v0.0.1
          command: ["php", "artisan", "migrate", "--force"]
          envFrom:
            - configMapRef:
                name: users-config
            - secretRef:
                name: users-secret
